/*
 * This file is generated by jOOQ.
 */
package com.jhy.jooq.generator;


import com.jhy.jooq.generator.tables.FlywaySchemaHistory;
import com.jhy.jooq.generator.tables.UserRole;
import com.jhy.jooq.generator.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in jooq
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooq.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * 用户信息详情
     */
    public static final User USER = User.USER;

    /**
     * 用户权限
     */
    public static final UserRole USER_ROLE = UserRole.USER_ROLE;
}
