server: 
  port: 8081

spring: 
  datasource: 
    url: jdbc:mysql://localhost:3306/jooq?characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    baseline-on-migrate: true