/*
 * This file is generated by jOOQ.
 */
package com.jhy.jooq.generator.tables.daos;


import com.jhy.jooq.generator.tables.records.UserRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 用户信息详情
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDao extends DAOImpl<UserRecord, com.jhy.jooq.generator.tables.pojos.User, String> {

    /**
     * Create a new UserDao without any configuration
     */
    public UserDao() {
        super(com.jhy.jooq.generator.tables.User.USER, com.jhy.jooq.generator.tables.pojos.User.class);
    }

    /**
     * Create a new UserDao with an attached configuration
     */
    public UserDao(Configuration configuration) {
        super(com.jhy.jooq.generator.tables.User.USER, com.jhy.jooq.generator.tables.pojos.User.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.jhy.jooq.generator.tables.pojos.User object) {
        return object.getUserId();
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.jhy.jooq.generator.tables.pojos.User> fetchByUserId(String... values) {
        return fetch(com.jhy.jooq.generator.tables.User.USER.USER_ID, values);
    }

    /**
     * Fetch a unique record that has <code>user_id = value</code>
     */
    public com.jhy.jooq.generator.tables.pojos.User fetchOneByUserId(String value) {
        return fetchOne(com.jhy.jooq.generator.tables.User.USER.USER_ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.jhy.jooq.generator.tables.pojos.User> fetchByName(String... values) {
        return fetch(com.jhy.jooq.generator.tables.User.USER.NAME, values);
    }

    /**
     * Fetch records that have <code>intro IN (values)</code>
     */
    public List<com.jhy.jooq.generator.tables.pojos.User> fetchByIntro(String... values) {
        return fetch(com.jhy.jooq.generator.tables.User.USER.INTRO, values);
    }
}
