/*
 * This file is generated by jOOQ.
 */
package com.jhy.jooq.generator.tables.daos;


import com.jhy.jooq.generator.tables.UserRole;
import com.jhy.jooq.generator.tables.records.UserRoleRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 用户权限
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRoleDao extends DAOImpl<UserRoleRecord, com.jhy.jooq.generator.tables.pojos.UserRole, String> {

    /**
     * Create a new UserRoleDao without any configuration
     */
    public UserRoleDao() {
        super(UserRole.USER_ROLE, com.jhy.jooq.generator.tables.pojos.UserRole.class);
    }

    /**
     * Create a new UserRoleDao with an attached configuration
     */
    public UserRoleDao(Configuration configuration) {
        super(UserRole.USER_ROLE, com.jhy.jooq.generator.tables.pojos.UserRole.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.jhy.jooq.generator.tables.pojos.UserRole object) {
        return object.getUserId();
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.jhy.jooq.generator.tables.pojos.UserRole> fetchByUserId(String... values) {
        return fetch(UserRole.USER_ROLE.USER_ID, values);
    }

    /**
     * Fetch a unique record that has <code>user_id = value</code>
     */
    public com.jhy.jooq.generator.tables.pojos.UserRole fetchOneByUserId(String value) {
        return fetchOne(UserRole.USER_ROLE.USER_ID, value);
    }

    /**
     * Fetch records that have <code>role_id IN (values)</code>
     */
    public List<com.jhy.jooq.generator.tables.pojos.UserRole> fetchByRoleId(String... values) {
        return fetch(UserRole.USER_ROLE.ROLE_ID, values);
    }
}
